language: node_js
node_js:
    - "0.10"
before_install:
    - sudo apt-get update -y
    - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
    - sudo apt-get -y remove postgis
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update -y
    - sudo apt-get install -y gdal-bin
    